---
# defaults file for Graphite
ansible_operator_meta:
  namespace: graphite

state: present
graphite_timezone: Europe/Berlin
graphite_version: "1.1.7"
graphite_image: "graphiteapp/graphite-statsd:{{ graphite_version }}-9"

graphite_cm_name: "graphite-configmap"
graphite_web_cm_name: "graphite-web-configmap"
graphite_web_secret_name: "graphite-web-htpasswd-secret"
  #graphite_relay_cm_name: "graphite-relay-configmap"
graphite_statsd_cm_name: "graphite-statsd-configmap"

graphite_service_account: "deployer"

graphite_readiness_timeout: 5
graphite_liveness_timeout: 5

graphite_carbon_node_count: 1
graphite_carbon_node_image: "{{ graphite_image }}"
graphite_carbon_node_ss_name: "graphite-carbon-node"
graphite_carbon_node_svc_name: "graphite-carbon-node"
graphite_carbon_node_use_gocarbon: true
graphite_carbon_node_pvc_access_mode: ["ReadWriteOnce"]
graphite_carbon_node_pvc_storage_class_name: "local-storage"
graphite_carbon_node_pvc_size: "10Gi"

graphite_carbon_node_port_pickle: 2004
graphite_carbon_node_port_line: 2003
graphite_carbon_node_resources:
  limits:
    cpu: 2
    memory: 4G
  requests:
    cpu: 200m
    memory: 512Mi
graphite_carbon_readiness_timeout: 5
graphite_carbon_liveness_timeout: 5

graphite_relay_count: 1
graphite_carbon_relay_image: "{{ graphite_image }}"
graphite_relay_ss_name: "graphite-relay"
graphite_relay_svc_name: "graphite-carbon-relay"
graphite_relay_port_pickle: 2014
graphite_relay_port_line: 2013
graphite_relay_replication_factor: 1
graphite_relay_normalize_tag: true
  #graphite_relay_enable_aggregation: false
graphite_relay_destination_port: "{{ graphite_carbon_node_port_pickle }}"
graphite_relay_resources: 
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 100m
    memory: 512Mi
graphite_relay_readiness_timeout: 5
graphite_relay_liveness_timeout: 5

graphite_aggregator_port_pickle: 2024
graphite_aggregator_replication_factor: 1

graphite_carbon_storage_stats_retentions: "10s:6h,1m:6d,10m:1y"
graphite_carbon_storage_default_retentions: "60s:1d,5m:30d,1h:3y"

graphite_statsd_image: "quay.io/opentelekomcloud/statsd:v0.9.0"
graphite_statsd_svc_name: "graphite-statsd"
graphite_statsd_ss_name: "graphite-statsd"
graphite_statsd_protocol: "UDP"
graphite_statsd_resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
graphite_statsd_readiness_timeout: 5
graphite_statsd_liveness_timeout: 5

graphite_web_count: 1
graphite_web_svc_name: "graphite-web"
graphite_web_ss_name: "graphite-web"
graphite_web_image: "{{ graphite_image }}"
graphite_web_resources: 
  limits:
    cpu: 1
    memory: 2G
  requests:
    cpu: 100m
    memory: 500Mi
graphite_web_readiness_timeout: 5
graphite_web_liveness_timeout: 5

graphite_memcached_count: 1
graphite_memcached_image: "quay.io/opentelekomcloud/memcached:1.6-alpine"
graphite_memcached_svc_name: "graphite-memcached"
graphite_memcached_ss_name: "graphite-memcached"
graphite_memcached_resources: 
  requests:
    cpu: 50m
    memory: 64Mi
