# permissions for end users to view graphites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graphite-viewer-role
rules:
- apiGroups:
  - database.otc.com
  resources:
  - graphites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.otc.com
  resources:
  - graphites/status
  verbs:
  - get
