# permissions for end users to edit graphites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graphite-editor-role
rules:
- apiGroups:
  - database.otc.com
  resources:
  - graphites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.otc.com
  resources:
  - graphites/status
  verbs:
  - get
