apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: graphite-operator.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: graphiteapp operator
  displayName: graphite-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - graphiteapp
  links:
  - name: Graphite Operator
    url: https://graphite-operator.eco.tsi-dev.otc-service.com
  maintainers:
  - email: artem.goncharov@t-systems.com
    name: Artem Goncharov
  maturity: alpha
  provider:
    name: Open Telekom Cloud
  version: 0.0.3
